requires 'Carp';
requires 'Data::Dumper';
requires 'Digest::SHA';
requires 'Encode';
requires 'Log::Log4perl';
requires 'List::MoreUtils';

requires 'File::Slurp';
requires 'HTML::Entities';
requires 'HTML::Parser';
requires 'HTML::Template';
requires 'HTML::Template::Compiled';
requires 'HTTP::Daemon';
requires 'Net::Async::HTTP::Server';

requires 'Image::Magick', '>= 6.0, < 7.000';
requires 'Image::Resize';
requires 'IO::Compress::Gzip';
requires 'IO::Handle';
requires 'IO::Select';
requires 'IO::Async';
requires 'JSON';
requires 'LWP::MediaTypes';
requires 'LWP::UserAgent';
requires 'MIME::Base64';
requires 'MIME::Types';
requires 'File::MimeInfo::Magic';
requires 'POSIX';
requires 'POSIX';
requires 'SOAP::Lite';
requires 'Socket';
requires 'Time::HiRes';
requires 'UPnP::ControlPoint';
requires 'URI::Escape';

requires 'XML::Simple';
requires 'XML::Liberal';
requires 'XML::LibXML::Simple';

requires 'JSON::XS';
requires 'Text::Table';
requires 'IO::Scalar';
requires 'Scalar::Util::Numeric';
